{ lib, pkgs, site, hostInventory, hostName, ... }:
let
  radicleOrg = lib.attrByPath [ "org" "network" "radicle" ] { } hostInventory;
  yggAddress = lib.attrByPath [
    "networks"
    "privateYggdrasil"
    "nodes"
    hostName
    "address"
  ] null site;
  nodePort = radicleOrg.port or (lib.attrByPath [ "ports" "radicleNode" "port" ] 8776 site);
  yggIfName = lib.attrByPath [
    "networks"
    "privateYggdrasil"
    "defaults"
    "ifName"
  ] "ygg0" site;
  privateKeyFile = radicleOrg.privateKeyFile or null;
  serviceEnabled = privateKeyFile != null;
  # Raw bind address (IPv6 Ygg or loopback fallback).
  bindAddr = if yggAddress != null then yggAddress else "127.0.0.1";
  # Socket address: IPv6 addresses need brackets, IPv4/loopback do not.
  listenAddr =
    if yggAddress != null then
      "[${bindAddr}]:${toString nodePort}"
    else
      "${bindAddr}:${toString nodePort}";
in
{
  # Disable the upstream NixOS radicle module — it requires publicKey to be
  # known at eval time but ours is generated on first boot. We manage the
  # service directly below.
  disabledModules = [ "services/misc/radicle.nix" ];

  assertions = [
    {
      assertion = !(builtins.elem "radicle-seed" (hostInventory.roles or [ ])) || privateKeyFile != null;
      message = ''
        Host "${hostName}" claims role "radicle-seed" but
        org.network.radicle.privateKeyFile is not set.
        Set it to the on-disk key path (generated by the radicle-keygen oneshot).
      '';
    }
  ];

  # Manage Radicle as a plain systemd service. The key at privateKeyFile is
  # generated on first boot by the radicle-keygen oneshot in bootstrap.nix.
  systemd.services.radicle-seed = lib.mkIf serviceEnabled {
    description = "Radicle seed node (cluster fabric)";
    wantedBy = [ "multi-user.target" ];
    after = [
      "network-online.target"
      "radicle-keygen.service"
    ];
    wants = [ "network-online.target" ];
    requires = [ "radicle-keygen.service" ];
    environment = {
      RAD_HOME = "/var/lib/radicle";
      GIT_AUTHOR_EMAIL = "radicle@${hostName}";
    };
    serviceConfig = {
      ExecStart = lib.concatStringsSep " " [
        "${lib.getExe' pkgs.radicle-node "radicle-node"}"
        "--listen"
        listenAddr
      ];
      Restart = "on-failure";
      RestartSec = "5s";
      User = "radicle";
      Group = "radicle";
      PrivateTmp = true;
      ProtectSystem = "strict";
      ReadWritePaths = [ "/var/lib/radicle" ];
      NoNewPrivileges = true;
    };
  };

  users.groups.radicle = lib.mkIf serviceEnabled { };
  users.users.radicle = lib.mkIf serviceEnabled {
    isSystemUser = true;
    group = "radicle";
    description = "Radicle service account";
    home = "/var/lib/radicle";
    createHome = true;
  };

  # Open Radicle port only on the private overlay interface.
  networking.firewall.interfaces.${yggIfName}.allowedTCPPorts = lib.mkIf serviceEnabled [ nodePort ];
}
