{ lib, site, hostInventory, ... }:
let
  fabric = site.storageFabric or { };
  annexCfg = fabric.annex or { };
  archiveCfg = fabric.archive or { };
  numCopies = annexCfg.defaultNumCopies or 2;
  minArchiveCopies = archiveCfg.minArchiveCopies or 2;
  isArchiveNode = builtins.elem "archive-node" (hostInventory.roles or [ ]);
in
lib.mkIf isArchiveNode {
  # Policy notes (enforced via git-annex configuration, not NixOS options):
  #
  # numcopies = ${toString numCopies}
  #   A file may be dropped from any single remote only if at least
  #   ${toString numCopies} other copies exist.
  #
  # required = archive
  #   Archive-group remotes are listed as required remotes.  git-annex will
  #   refuse to drop the last copy in the archive group.
  #
  # These settings must be initialised by `cluster-annex init` on first run.
  # They are not yet expressible as NixOS module options because git-annex
  # stores policy inside the git repo.

  environment.etc."cluster-annex/policy.conf".text = ''
    # Generated by storage/archive dendrite.  Do not edit by hand.
    numcopies=${toString numCopies}
    minarchivecopies=${toString minArchiveCopies}
  '';
}
