{
  lib,
  pkgs,
  site,
  hostName,
  ...
}:
let
  fabric = site.storageFabric or { };
  annexCfg = fabric.annex or { };
  annexUser = annexCfg.user or "annex";
  repoRoot = annexCfg.repoRoot or "/srv/annex/cluster-data";
  annexSshKey = "${repoRoot}/.ssh/id_ed25519";
  privateYggNodes = lib.attrByPath [ "networks" "privateYggdrasil" "nodes" ] { } site;
  yggAliases = lib.concatMap (node: node.aliases or [ ]) (builtins.attrValues privateYggNodes);

  # Collect declared annex SSH public keys from all peers in inventory.
  # Each host that participates in the annex fabric can declare its key via
  # org.storage.annex.sshPublicKey after first-boot keygen.
  isAnnexPeer =
    h:
    let
      fabricOrg = lib.attrByPath [ "org" "storage" "annex" "fabric" ] { } (
        (site.hosts or { }).${h} or { }
      );
    in
    (fabricOrg.storage or false)
    || (fabricOrg.client or false)
    || (fabricOrg.workstation or false)
    || (fabricOrg.computeCache or false);
  isPeerHost = h: h != hostName && isAnnexPeer h;
  peerHosts = builtins.filter isPeerHost (builtins.attrNames (site.hosts or { }));
  peerAuthorizedKeys = lib.concatMap (
    peerName:
    let
      peerKey = lib.attrByPath [ "org" "storage" "annex" "sshPublicKey" ] null (
        site.hosts.${peerName} or { }
      );
    in
    lib.optional (peerKey != null) peerKey
  ) peerHosts;
in
{
  # Restrict the annex SSH service account to git-annex-shell only.
  # No interactive login.  Authorized keys are added per-host via
  # org.storage.annex.sshKeys or the host override module.
  services.openssh.extraConfig = ''
    Match User ${annexUser}
      ForceCommand ${lib.getExe' pkgs.git-annex "git-annex-shell"} -d /
      AllowAgentForwarding no
      AllowTcpForwarding no
      X11Forwarding no
      PermitTTY no
  '';

  # SSH client config: annex remote names ending in -ygg resolve to the
  # Yggdrasil address.  Only *-ygg host aliases are accepted for annex
  # remotes (enforced by lib/validation/storage-fabric.nix).
  # IdentityFile points to the per-host annex keypair generated by
  # leaves/systemd.nix on first boot.
  programs.ssh.extraConfig = lib.optionalString (yggAliases != [ ]) (
    lib.concatMapStringsSep "\n" (alias: ''
      Host ${alias}
        User ${annexUser}
        IdentityFile ${annexSshKey}
        IdentitiesOnly yes
        StrictHostKeyChecking accept-new
    '') yggAliases
  );

  # Peer annex public keys → authorized on this host's annex service account.
  users.users.${annexUser}.openssh.authorizedKeys.keys = peerAuthorizedKeys;
}
